from src.domain.exeption.base import DomainError


class LogIpError(DomainError): ...


class LogGeoError(DomainError): ...


class LogDatetimeError(DomainError): ...


class LogRequestMethodError(DomainError): ...


class LogProtocolError(DomainError): ...


class LogUriError(DomainError): ...


class LogPriError(DomainError): ...
