from domain.interfaces.event_bus import iEventBus


class EnrichLogHandler:
    def __init__(self, event_bus: iEventBus) -> None:
        self.event_bus = event_bus

    async def execute(self, raw_log: dict) -> None:
        geo_service = ...
        uuid_service = ...

        uc_init = ...
        uc_execute = ...

        if uc_execute is not None:
            event_bus_execute = ...
        ...